Lint/AssignmentInCondition:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/SingleLineBlockParams:
  Enabled: false

Style/SignalException:
  Enabled: false
