name: adventofcode

type: go

up:
  - go:
      version: 1.15.6

# `dev run` runs `dev build` and then `dev run-built` if these are both defined.
commands:
  build:
    run: go build -o bin/adventofcode cmd/main.go
  run-built:
    desc: |
      Run the target after `dev build`.
      `dev run` is a special command that will run `dev build` and then `dev run-built` if they are both defined.
    run: bin/adventofcode
  test:
    run: go test -v ./pkg/advent
  style:
    run: golint ./...
  profile:
    run: go test -v ./pkg/advent -cpuprofile cpu.prof -memprofile mem.prof
