up:
  - rust:
      version: stable

env:
  CARGO_PROFILE_RELEASE_DEBUG: "true"

commands:
  build:
    desc: Build the project
    run: cargo build

  run-built:
    desc: Run the built project
    run: target/debug/adventofcode

  style:
    desc: Run rustfmt
    run: cargo fmt

  test:
    desc: Run tests
    run: cargo test

  profile:
    desc: Profile and produce flamegraph
    run: |
      cargo flamegraph --root --deterministic
      open flamegraph.svg
