name: adventofcode

up:
  - go:
      version: 1.23.3
      modules: true
  - ruby
  - bundler

commands:
  test:
    run: |
      make test
      bin/rake test
  generate:
    run: |
      [ -z "$1" ] && echo "Usage: dev generate DAY" && exit 1
      bin/rake generate[$1]
